server:
  BindAddress: "0.0.0.0:4180"

upstreamConfig:
  upstreams:
    - id: "caddy"
      path: /
      static: true
      staticCode: 200

providers:
  - id: "authentik"
    provider: "oidc"
    clientID: "AUTHENTIK_CLIENT_ID"
    clientSecret: "AUTHENTIK_CLIENT_SECRET"
    oidcConfig:
      issuerURL: "https://authentik.MYDOMAIN.TLD/application/o/zed/"
      enabledSigningAlgs:
        - "RS256"
        - "ES256"
    profileURL: "https://authentik.MYDOMAIN.TLD/application/o/userinfo/"
    scope: "email openid profile friendly_name groups entitlements"
    code_challenge_method: "S256"
    additionalClaims:
      - "name"
      - "given_name"
      - "roles"
      - "entitlements"
      - "groups"
      - "friendly_name"
      - "email_verified"

# injectRequestHeaders:
injectResponseHeaders:
  #############################
  # Standard Headers          #
  #############################
  - name: "X-Auth-Request-User"
    values:
      - claimSource: { claim: "name" }
  - name: "X-Auth-Request-Preferred-Username"
    values:
      - claimSource: { claim: "preferred_username" }
  - name: "X-Auth-Request-Username"
    values:
      - claimSource: { claim: "preferred_username" }
  - name: "X-Auth-Request-Email"
    values:
      - claimSource: { claim: "email" }
  - name: "X-Auth-Request-Groups"
    values:
      - claimSource: { claim: "groups" }

  #############################
  # Non-Standard Headers
  #############################
  - name: "X-Auth-Request-Roles"
    values:
      - claimSource: { claim: "roles" }

  - name: "X-Auth-Request-Entitlements"
    values:
      - claimSource: {claim: "entitlements" }

  - name: "X-Auth-Request-Friendly-Name"
    values:
      - claimSource: { claim: "friendly_name" }

  - name: "X-Auth-Request-Email-Verified"
    values:
      - claimSource: { claim: "email_verified" }
